language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: required
dist: trusty
group: edge

env:
  - NODE_VERSION=6.x
  - NODE_VERSION=7.x

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.composer/cache/files

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"
  - composer self-update
  - npm install grunt-cli yarn -g

install:
  - travis_retry composer install --no-interaction --prefer-source
  - npm install
  - grunt build

script: ./bin/phpunit --configuration phpunit.xml --coverage-text
